version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: astro_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./astro_backend
    container_name: astro_backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/astro_services
    depends_on:
      - mongo

  frontend:
    build: ./astro_services
    container_name: astro_frontend
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  mongo_data:
